import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextAuthProvider } from "@/components/Providers";
import { MatchesProvider } from "@/components/matchesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="mx-auto min-h-screen flex flex-col bg-gray-900 text-white p-4">
            <Navbar />
            <MatchesProvider>
              <div className="flex-auto">{children}</div>
              <Footer />
            </MatchesProvider>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
